stages:
  - test
  - release

image: registry.gitlab.com/lumoslabs/docker-library/golang:1.11-ci

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor

before_script:
  - |
    if test -d vendor ; then
      mkdir -vp $GOPATH/pkg/mod
      cp -r vendor/* $GOPATH/pkg/mod/
    else
      go mod download
    fi

after_script: 
  - go mod vendor

test:
  stage: test
  tags: [k8s]
  script: make test

test:race:
  stage: test
  tags: [k8s]
  script: make test-race

test:memory:
  stage: test
  tags: [k8s]
  script: make test-memory

release:test:
  stage: release
  tags: [k8s]
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://127.0.0.1:2375/
    DOCKER_DRIVER: overlay2
  script:
    - echo "$QUAY_PASSWORD" | docker login --username="$QUAY_USERNAME" --password-stdin quay.io
    - echo "$CI_JOB_TOKEN" | docker login --username=gitlab-ci-token --password-stdin $CI_REGISTRY
    - goreleaser release --rm-dist --snapshot

release:
  stage: release
  tags: [k8s]
  only:
    - tags
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://127.0.0.1:2375/
    DOCKER_DRIVER: overlay2
  script:
    - echo "$QUAY_PASSWORD" | docker login --username="$QUAY_USERNAME" --password-stdin quay.io
    - echo "$CI_JOB_TOKEN" | docker login --username=gitlab-ci-token --password-stdin $CI_REGISTRY
    - goreleaser release --rm-dist