before:
  hooks:
    - go mod download
builds:
- env: ["CGO_ENABLED=0"]
  main: ./cmd/vest/main.go
  binary: vest-{{.Os}}-{{.Arch}}
archive:
  files: ["none*"]
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
# checksum:
#   name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
