builds:
- env: ["CGO_ENABLED=0"]
  main: ./cmd/vest
  binary: vest
archive:
  files: ["none*"]
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
      - "quay.io/lumoslabs/vestibule:{{ .Tag }}"
      - "quay.io/lumoslabs/vestibule:{{ .Major }}"
      - "quay.io/lumoslabs/vestibule:{{ .Major }}.{{ .Minor }}"
      - "quay.io/lumoslabs/vestibule:latest"
      - "registry.gitlab.com/lumoslabs/vestibule:{{ .Tag }}"
      - "registry.gitlab.com/lumoslabs/vestibule:{{ .Major }}"
      - "registry.gitlab.com/lumoslabs/vestibule:{{ .Major }}.{{ .Minor }}"
      - "registry.gitlab.com/lumoslabs/vestibule:latest"